version: "3.3"

services:
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    restart: always
     
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin2023
      - POSTGRES_DB=temp_work
   
volumes:
      pgdata:
         driver: local
    
     
     
     
# Connect to DataBase     
# psql --host=localhost --username=dbuser --dbname=temp_work     
     
